name: CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Rust Stable
        run: rustup toolchain install stable --profile minimal
      - name: Setup Rust Nightly
        run: rustup toolchain install nightly --allow-downgrade -c rustfmt
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
          cache-all-crates: "true"
          key: ${{ runner.os }}-cargo-rust_stable-${{ hashFiles('**/Cargo.toml') }}
      - name: Format
        run: cargo +nightly fmt --all --check
      - name: Documentation
        env:
          DOCS_RS: 1
        run: cargo +nightly doc --all-features
      - name: Linting
        run: cargo clippy

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
       - uses: Swatinem/rust-cache@v2
         with:
          cache-on-failure: "true"
          cache-all-crates: "true"
       - name: Publish crates
         uses: katyo/publish-crates@v2
         with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
